"""Bounded anonymous read-only neuPrint retrieval. No authentication handling.
Only literal read queries generated by this project; retain exact request/response.
"""

import hashlib
import json
import re
from pathlib import Path
from urllib.request import Request, urlopen

URL = "https://neuprint.janelia.org/api/custom/custom"
MAX_BYTES = 2 * 1024 * 1024


def retrieve(cypher, out):
    if (
        not cypher.startswith("MATCH ")
        or "RETURN " not in cypher
        or not re.search(r"LIMIT [0-9]+$", cypher)
        or re.search(
            r"\b(CREATE|DELETE|SET|MERGE|REMOVE|CALL|LOAD|DROP)\b", cypher, re.I
        )
    ):
        raise ValueError("Read query required")
    limit = int(re.search(r"LIMIT ([0-9]+)$", cypher).group(1))
    if not 1 <= limit <= 16385 or len(cypher) > 65536 or ";" in cypher:
        raise ValueError("Query allocation cap")
    out = Path(out)
    if out.exists():
        raise ValueError("Preserve existing evidence")
    request = {"dataset": "male-cns:v1.0", "cypher": cypher}
    payload = json.dumps(request).encode()
    with urlopen(
        Request(URL, data=payload, headers={"Content-Type": "application/json"}),
        timeout=60,
    ) as response:
        raw = response.read(MAX_BYTES + 1)
        if len(raw) > MAX_BYTES:
            raise ValueError("Response exceeds 2 MiB hard cap")
        if response.status != 200:
            raise ValueError("Query failed")
    result = json.loads(raw)
    if "error" in result or not isinstance(result.get("data"), list):
        raise ValueError(
            "Query response invalid: " + str(result.get("error", "schema"))
        )
    if len(result["data"]) > limit:
        raise ValueError("Response row cap")
    out.mkdir(parents=True)
    (out / "request.json").write_bytes(payload)
    (out / "response.json").write_bytes(raw)
    record = {
        "url": URL,
        "dataset": request["dataset"],
        "query": cypher,
        "requestSha256": hashlib.sha256(payload).hexdigest(),
        "responseSha256": hashlib.sha256(raw).hexdigest(),
        "bytes": len(raw),
        "rows": len(result["data"]),
    }
    (out / "evidence.json").write_text(json.dumps(record, indent=2) + "\n")
    return result


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 4 or sys.argv[1] != "--allow-network":
        raise SystemExit(
            "Usage: query_malecns.py --allow-network query.json new-output-directory"
        )
    q = json.loads(Path(sys.argv[2]).read_text())
    if q.get("dataset") != "male-cns:v1.0":
        raise ValueError("Release must be male-cns:v1.0")
    result = retrieve(q["cypher"], sys.argv[3])
    print(json.dumps({"rows": len(result["data"]), "output": sys.argv[3]}))
